[package]
name = "genesis-lua"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
genesis-types = { path = "../genesis-types" }
mlua.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
