use serde::{Deserialize, Serialize};

/// Role of a participant in a conversation, following the OpenAI Chat Completions format.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConversationRole {
    /// System-level instructions that guide the assistant's behavior.
    System,
    /// A message from the human user.
    User,
    /// A response generated by the LLM.
    Assistant,
    /// Output returned from a tool call execution.
    Tool,
}

/// A single message in a conversation, pairing a role with text content.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ConversationMessage {
    /// Who produced this message.
    pub role: ConversationRole,
    /// The text body of the message.
    pub content: String,
}

/// Platform through which a session was initiated or a message will be delivered.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DeliveryPlatform {
    /// Local terminal / command-line interface.
    Cli,
    /// Direct HTTP API call.
    Api,
    /// Telegram Bot API.
    Telegram,
    /// Discord interactions webhook.
    Discord,
    /// Slack Events API.
    Slack,
    /// Home Assistant webhook integration.
    HomeAssistant,
    /// WhatsApp Cloud API.
    WhatsApp,
    /// Signal messenger.
    Signal,
}

impl std::fmt::Display for DeliveryPlatform {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Cli => write!(f, "cli"),
            Self::Api => write!(f, "api"),
            Self::Telegram => write!(f, "telegram"),
            Self::Discord => write!(f, "discord"),
            Self::Slack => write!(f, "slack"),
            Self::HomeAssistant => write!(f, "homeassistant"),
            Self::WhatsApp => write!(f, "whatsapp"),
            Self::Signal => write!(f, "signal"),
        }
    }
}

/// Identifies the LLM provider backend used for inference.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ModelProviderKind {
    /// OpenAI's first-party API.
    OpenAi,
    /// OpenRouter multi-provider routing service.
    OpenRouter,
    /// Anthropic's Claude API.
    Anthropic,
    /// Google Gemini API.
    Gemini,
    /// A locally-hosted model (e.g. llama.cpp, Ollama).
    Local,
    /// Any OpenAI-compatible third-party endpoint.
    Compatible,
}

/// Fully resolved model configuration: which provider, model name, and optional base URL.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ModelSelection {
    /// The LLM provider to route requests through.
    pub provider: ModelProviderKind,
    /// Provider-specific model identifier (e.g. `"gpt-4o"`, `"claude-sonnet-4-20250514"`).
    pub model: String,
    /// Custom API base URL, overriding the provider's default endpoint.
    pub base_url: Option<String>,
}

/// Schema definition for a tool that can be offered to the LLM for function calling.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolDefinition {
    /// Unique tool name used in tool-call requests and responses.
    pub name: String,
    /// Human-readable description shown to the LLM to explain what the tool does.
    pub description: String,
    /// JSON Schema describing the tool's accepted parameters, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// Events emitted during agent execution for observability and streaming.
///
/// Serialized as tagged JSON (`"event": "variant_name"`) for SSE and logging consumers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum RuntimeEvent {
    /// A new session has been created.
    SessionStarted { session_id: String },
    /// The model to use for this session has been resolved.
    ModelSelected { provider: String, model: String },
    /// Session is fully planned and ready to execute (model, platform, and session known).
    SessionPlanned {
        session_id: String,
        platform: DeliveryPlatform,
        provider: String,
        model: String,
    },
    /// An incremental chunk of the LLM's streamed response.
    TokenStream { chunk: String },
    /// The LLM has requested a tool call that is about to be executed.
    ToolCallRequested { tool_name: String },
    /// A tool call has finished executing.
    ToolCallCompleted {
        tool_name: String,
        /// Whether the tool executed without error.
        success: bool,
    },
    /// The scheduler has fired a cron job.
    SchedulerTick { job_id: String },
    /// A message has been queued for delivery to an external platform.
    DeliveryQueued {
        platform: DeliveryPlatform,
        destination: String,
    },
}

// These types were originally public but have zero callers outside this crate's
// test module. They are kept behind #[cfg(test)] until an external consumer needs them.
#[cfg(test)]
mod provider_types {
    use super::{ConversationMessage, ModelSelection, ToolDefinition};
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
    pub struct ProviderTurnRequest {
        pub session_id: String,
        pub model: ModelSelection,
        pub messages: Vec<ConversationMessage>,
        pub tools: Vec<ToolDefinition>,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    #[serde(rename_all = "snake_case")]
    pub enum StopReason {
        EndTurn,
        ToolCall,
        MaxTokens,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub struct UsageStats {
        pub input_tokens: u32,
        pub output_tokens: u32,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    pub struct ProviderTurnResponse {
        pub message: ConversationMessage,
        pub stop_reason: StopReason,
        pub usage: UsageStats,
    }
}

#[cfg(test)]
mod tests {
    use super::provider_types::{
        ProviderTurnRequest, ProviderTurnResponse, StopReason, UsageStats,
    };
    use super::{
        ConversationMessage, ConversationRole, DeliveryPlatform, ModelProviderKind, ModelSelection,
        RuntimeEvent, ToolDefinition,
    };

    #[test]
    fn runtime_events_round_trip_through_json() {
        let event = RuntimeEvent::SessionPlanned {
            session_id: "session-123".to_owned(),
            platform: DeliveryPlatform::Slack,
            provider: "openrouter".to_owned(),
            model: "moonshotai/kimi-k2".to_owned(),
        };

        let encoded = serde_json::to_string(&event).expect("event should serialize");
        let decoded: RuntimeEvent =
            serde_json::from_str(&encoded).expect("event should deserialize");

        assert_eq!(decoded, event);
    }

    #[test]
    fn provider_turn_payloads_round_trip_through_json() {
        let request = ProviderTurnRequest {
            session_id: "session-123".to_owned(),
            model: ModelSelection {
                provider: ModelProviderKind::OpenRouter,
                model: "moonshotai/kimi-k2".to_owned(),
                base_url: Some("https://openrouter.ai/api/v1".to_owned()),
            },
            messages: vec![ConversationMessage {
                role: ConversationRole::User,
                content: "Summarize the last run.".to_owned(),
            }],
            tools: vec![ToolDefinition {
                name: "session_search".to_owned(),
                description: "Searches prior sessions".to_owned(),
                parameters: None,
            }],
        };

        let response = ProviderTurnResponse {
            message: ConversationMessage {
                role: ConversationRole::Assistant,
                content: "Here is the summary.".to_owned(),
            },
            stop_reason: StopReason::EndTurn,
            usage: UsageStats {
                input_tokens: 128,
                output_tokens: 64,
            },
        };

        let encoded_request =
            serde_json::to_string(&request).expect("request should serialize cleanly");
        let decoded_request: ProviderTurnRequest =
            serde_json::from_str(&encoded_request).expect("request should deserialize");
        let encoded_response =
            serde_json::to_string(&response).expect("response should serialize cleanly");
        let decoded_response: ProviderTurnResponse =
            serde_json::from_str(&encoded_response).expect("response should deserialize");

        assert_eq!(decoded_request, request);
        assert_eq!(decoded_response, response);
    }

    #[test]
    fn delivery_platform_display_matches_snake_case() {
        assert_eq!(DeliveryPlatform::Cli.to_string(), "cli");
        assert_eq!(DeliveryPlatform::Api.to_string(), "api");
        assert_eq!(DeliveryPlatform::Telegram.to_string(), "telegram");
        assert_eq!(DeliveryPlatform::Discord.to_string(), "discord");
        assert_eq!(DeliveryPlatform::Slack.to_string(), "slack");
        assert_eq!(DeliveryPlatform::HomeAssistant.to_string(), "homeassistant");
        assert_eq!(DeliveryPlatform::WhatsApp.to_string(), "whatsapp");
        assert_eq!(DeliveryPlatform::Signal.to_string(), "signal");
    }
}
