[package]
name = "genesis-tui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
genesis-ui.path = "../genesis-ui"
genesis-core.path = "../genesis-core"
genesis-storage.path = "../genesis-storage"
genesis-types.path = "../genesis-types"
genesis-config.path = "../genesis-config"
ratatui.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }
tokio = { workspace = true, features = ["rt", "macros", "signal", "sync"] }
syntect.workspace = true
image.workspace = true
unicode-width.workspace = true
thiserror.workspace = true
tracing.workspace = true
dirs.workspace = true
futures-util.workspace = true
libc.workspace = true

[dev-dependencies]
