[package]
name = "genesis-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
dirs.workspace = true
futures-util.workspace = true
hex.workspace = true
genesis-auth = { path = "../genesis-auth" }
genesis-config = { path = "../genesis-config" }
genesis-mcp = { path = "../genesis-mcp" }
genesis-provider = { path = "../genesis-provider" }
genesis-storage = { path = "../genesis-storage" }
genesis-tools = { path = "../genesis-tools" }
genesis-types = { path = "../genesis-types" }
rand.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
insta = { workspace = true }
tempfile.workspace = true
tracing-test.workspace = true
