[package]
name = "genesis-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
futures-util.workspace = true
genesis-config = { path = "../genesis-config" }
genesis-provider = { path = "../genesis-provider" }
genesis-storage = { path = "../genesis-storage" }
genesis-tools = { path = "../genesis-tools" }
genesis-types = { path = "../genesis-types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
