//! HistoryCell — the sum type for all conversation history cells.

use ratatui::buffer::Buffer;
use ratatui::layout::Rect;
use ratatui::text::Line;

use super::agent_cell::AgentCell;
use super::tool_cell::ToolCell;
use super::user_cell::UserCell;

/// A single displayable unit in the conversation history.
///
/// Each variant wraps the cell-specific data and delegates rendering to the
/// underlying type.
#[derive(Debug, Clone)]
pub enum HistoryCell {
    /// A message typed by the user.
    User(UserCell),
    /// A response generated by the agent (Eve).
    Agent(AgentCell),
    /// A single tool invocation with timing and success/fail status.
    Tool(ToolCell),
}

impl HistoryCell {
    /// Render the cell into the given buffer area.
    pub fn render(&self, area: Rect, buf: &mut Buffer) {
        match self {
            HistoryCell::User(c) => c.render(area, buf),
            HistoryCell::Agent(c) => c.render(area, buf),
            HistoryCell::Tool(c) => c.render(area, buf),
        }
    }

    /// Return the number of rows this cell occupies at the given terminal width.
    pub fn height(&self, width: u16) -> u16 {
        match self {
            HistoryCell::User(c) => c.height(width),
            HistoryCell::Agent(c) => c.height(width),
            HistoryCell::Tool(c) => c.height(width),
        }
    }

    /// Produce the styled [`Line`]s for insertion into terminal scrollback.
    pub fn to_scrollback_lines(&self, width: u16) -> Vec<Line<'static>> {
        match self {
            HistoryCell::User(c) => c.to_scrollback_lines(width),
            HistoryCell::Agent(c) => c.to_scrollback_lines(width),
            HistoryCell::Tool(c) => c.to_scrollback_lines(width),
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;

    #[test]
    fn user_cell_height_via_enum() {
        let cell = HistoryCell::User(UserCell::new("hello world"));
        assert_eq!(cell.height(80), 1);
    }

    #[test]
    fn agent_cell_height_via_enum() {
        let cell = HistoryCell::Agent(AgentCell::new("hello world"));
        assert_eq!(cell.height(80), 1);
    }

    #[test]
    fn tool_cell_height_via_enum_grouped_default() {
        // Default display mode is Grouped (4 lines).
        let cell = HistoryCell::Tool(ToolCell::new(
            "shell",
            "c1",
            "ls",
            true,
            Duration::from_millis(500),
        ));
        assert_eq!(cell.height(80), 4);
        assert_eq!(cell.height(20), 4);
    }

    #[test]
    fn scrollback_lines_user() {
        let cell = HistoryCell::User(UserCell::new("hi there"));
        let lines = cell.to_scrollback_lines(80);
        assert_eq!(lines.len(), 1);
    }

    #[test]
    fn scrollback_lines_agent() {
        let cell = HistoryCell::Agent(AgentCell::new("hello from eve"));
        let lines = cell.to_scrollback_lines(80);
        assert_eq!(lines.len(), 1);
    }

    #[test]
    fn scrollback_lines_tool_grouped_default() {
        // Default display mode is Grouped — produces 4 lines.
        let cell = HistoryCell::Tool(ToolCell::new(
            "read_file",
            "c2",
            "path.txt",
            false,
            Duration::from_millis(300),
        ));
        let lines = cell.to_scrollback_lines(80);
        assert_eq!(lines.len(), 4);
    }

    #[test]
    fn wrapping_increases_height_user() {
        let long_text = "word ".repeat(30);
        let cell = HistoryCell::User(UserCell::new(long_text.trim()));
        let h = cell.height(30);
        assert!(h > 1, "expected wrapped height > 1, got {h}");
    }

    #[test]
    fn multiline_agent_cell_has_correct_height() {
        // Agent cells use markdown rendering (line-per-source-line, no word-wrap).
        let cell = HistoryCell::Agent(AgentCell::new("line one\nline two\nline three"));
        let h = cell.height(80);
        assert_eq!(h, 3, "expected 3 lines for 3-line markdown text, got {h}");
    }
}
