[package]
name = "genesis-config"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
