[package]
name = "genesis-tools"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
base64.workspace = true
genesis-provider = { path = "../genesis-provider" }
genesis-storage = { path = "../genesis-storage" }
genesis-types = { path = "../genesis-types" }
glob.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
url.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
