[package]
name = "genesis-tools"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
genesis-storage = { path = "../genesis-storage" }
genesis-types = { path = "../genesis-types" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
