//! Welcome screen widget with Eve half-block pixel art.
//!
//! Displays a bordered welcome screen with Eve's banner art and session info.
//! Adapts to three layout modes based on terminal width:
//! - Full (>= 100 cols): art left, info right, side-by-side in a bordered box
//! - Compact (60-99 cols): art centered above info in a bordered box
//! - Text-only (< 60 cols): just ">_ Eve v{version}" in accent color
//!
//! The art is animated with a gentle hip-sway effect: the source image is
//! shifted horizontally through an 8-frame cycle before rendering to
//! half-blocks, creating a smooth left-right motion.

use image::{DynamicImage, GenericImageView, Rgba, RgbaImage};
use ratatui::{
    buffer::Buffer,
    layout::Rect,
    style::{Color, Style},
    text::{Line, Span},
    widgets::{Block, BorderType, Borders, Paragraph, Widget},
};

use crate::history::rgb;

/// Minimum width for the full side-by-side layout.
const FULL_LAYOUT_MIN_WIDTH: u16 = 100;

/// Minimum width for the compact (stacked) layout.
const COMPACT_LAYOUT_MIN_WIDTH: u16 = 60;

/// Session info displayed on the welcome screen.
pub struct WelcomeInfo {
    pub model: String,
    pub cwd: String,
    pub version: String,
}

/// Horizontal pixel offsets for the 8-frame sway cycle.
///
/// The pattern `[0, 1, 2, 1, 0, -1, -2, -1]` creates a smooth left-right
/// pendulum motion.
const SWAY_OFFSETS: [i32; 8] = [0, 1, 2, 1, 0, -1, -2, -1];

/// Welcome screen widget showing Eve's banner art with session info.
pub struct WelcomeWidget {
    info: WelcomeInfo,
    /// Full-size sway animation frames (8 frames). Empty if image failed to load.
    full_frames: Vec<Vec<Line<'static>>>,
    /// Compact sway animation frames (8 frames). Empty if image failed to load.
    compact_frames: Vec<Vec<Line<'static>>>,
    /// Current animation frame index.
    current_frame: usize,
    /// Whether animation is enabled (true when we have frames).
    pub animated: bool,
}

impl WelcomeWidget {
    /// Create a new welcome widget by pre-parsing ANSI art into ratatui Lines.
    ///
    /// The `full_art` and `compact_art` slices are used as fallback frame 0
    /// if the raw images are unavailable. When images are available, sway
    /// frames are generated by horizontally shifting the source pixels.
    pub fn new(info: WelcomeInfo, full_art: &[String], compact_art: &[String]) -> Self {
        let full_img = genesis_ui::banner::full_image();
        let compact_img = genesis_ui::banner::compact_image();

        let (full_frames, compact_frames, animated) = match (full_img, compact_img) {
            (Some(fi), Some(ci)) => {
                let ff = generate_sway_frames(&fi);
                let cf = generate_sway_frames(&ci);
                (ff, cf, true)
            }
            _ => {
                // Fallback: single static frame from pre-rendered art.
                let ff = vec![parse_ansi_art(full_art)];
                let cf = vec![parse_ansi_art(compact_art)];
                (ff, cf, false)
            }
        };

        Self {
            info,
            full_frames,
            compact_frames,
            current_frame: 0,
            animated,
        }
    }

    /// Advance to the next animation frame.
    pub fn next_frame(&mut self) {
        if self.animated && !self.full_frames.is_empty() {
            self.current_frame = (self.current_frame + 1) % self.full_frames.len();
        }
    }

    /// Get the current full-size art lines.
    fn current_full_art(&self) -> &[Line<'static>] {
        if self.full_frames.is_empty() {
            &[]
        } else {
            &self.full_frames[self.current_frame % self.full_frames.len()]
        }
    }

    /// Get the current compact art lines.
    fn current_compact_art(&self) -> &[Line<'static>] {
        if self.compact_frames.is_empty() {
            &[]
        } else {
            &self.compact_frames[self.current_frame % self.compact_frames.len()]
        }
    }

    /// Render the welcome screen into the given area.
    pub fn render(&self, area: Rect, buf: &mut Buffer) {
        if area.width == 0 || area.height == 0 {
            return;
        }

        if area.width >= FULL_LAYOUT_MIN_WIDTH {
            self.render_full(area, buf);
        } else if area.width >= COMPACT_LAYOUT_MIN_WIDTH {
            self.render_compact(area, buf);
        } else {
            self.render_text_only(area, buf);
        }
    }

    /// Full layout: bordered box with art on left, info on right.
    fn render_full(&self, area: Rect, buf: &mut Buffer) {
        let block = Block::default()
            .borders(Borders::ALL)
            .border_type(BorderType::Rounded);

        let inner = block.inner(area);
        block.render(area, buf);

        if inner.width == 0 || inner.height == 0 {
            return;
        }

        // Compute art dimensions (visual width of longest line).
        let art = self.current_full_art();
        let art_width = art
            .iter()
            .map(|l| line_visual_width(l))
            .max()
            .unwrap_or(0) as u16;
        let art_height = art.len() as u16;

        // Art on the left, info on the right.
        let art_col_width = art_width.min(inner.width / 2);
        let info_col_x = inner.x + art_col_width + 2; // 2 cols gap
        let info_col_width = inner.width.saturating_sub(art_col_width + 2);

        // Center art vertically within the inner area.
        let art_y = inner.y + inner.height.saturating_sub(art_height) / 2;

        // Render art lines.
        let art_area = Rect {
            x: inner.x,
            y: art_y,
            width: art_col_width,
            height: art_height.min(inner.height),
        };
        let art_paragraph = Paragraph::new(art.to_vec());
        art_paragraph.render(art_area, buf);

        // Build info lines.
        let info_lines = self.info_lines();
        let info_height = info_lines.len() as u16;
        let info_y = inner.y + inner.height.saturating_sub(info_height) / 2;

        let info_area = Rect {
            x: info_col_x,
            y: info_y,
            width: info_col_width,
            height: info_height.min(inner.height),
        };
        let info_paragraph = Paragraph::new(info_lines);
        info_paragraph.render(info_area, buf);
    }

    /// Compact layout: bordered box with art centered above info.
    fn render_compact(&self, area: Rect, buf: &mut Buffer) {
        let block = Block::default()
            .borders(Borders::ALL)
            .border_type(BorderType::Rounded);

        let inner = block.inner(area);
        block.render(area, buf);

        if inner.width == 0 || inner.height == 0 {
            return;
        }

        let art_lines = self.current_compact_art();
        let art_height = art_lines.len() as u16;
        let info_lines = self.info_lines();
        let info_height = info_lines.len() as u16;
        let gap = 1u16;

        let total_content = art_height + gap + info_height;
        let start_y = inner.y + inner.height.saturating_sub(total_content) / 2;

        // Render compact art centered horizontally.
        let art_visual_width = art_lines
            .iter()
            .map(|l| line_visual_width(l))
            .max()
            .unwrap_or(0) as u16;
        let art_x = inner.x + inner.width.saturating_sub(art_visual_width) / 2;
        let art_area = Rect {
            x: art_x,
            y: start_y,
            width: art_visual_width.min(inner.width),
            height: art_height.min(inner.height),
        };
        let art_paragraph = Paragraph::new(art_lines.to_vec());
        art_paragraph.render(art_area, buf);

        // Render info below art, centered.
        let info_visual_width = info_lines
            .iter()
            .map(|l| line_visual_width(l))
            .max()
            .unwrap_or(0) as u16;
        let info_x = inner.x + inner.width.saturating_sub(info_visual_width) / 2;
        let info_y = start_y + art_height + gap;
        if info_y < inner.y + inner.height {
            let info_area = Rect {
                x: info_x,
                y: info_y,
                width: info_visual_width.min(inner.width),
                height: info_height.min(inner.y + inner.height - info_y),
            };
            let info_paragraph = Paragraph::new(info_lines);
            info_paragraph.render(info_area, buf);
        }
    }

    /// Text-only layout: just ">_ Eve v{version}" in accent color.
    fn render_text_only(&self, area: Rect, buf: &mut Buffer) {
        let accent = rgb(genesis_ui::colors::UI_ACCENT);
        let text = format!(">_ Eve v{}", self.info.version);
        let line = Line::from(Span::styled(text, Style::default().fg(accent)));

        // Center vertically and horizontally.
        let y = area.y + area.height / 2;
        let x = area.x + area.width.saturating_sub(line.width() as u16) / 2;
        if y < area.y + area.height {
            let text_area = Rect {
                x,
                y,
                width: area.width.saturating_sub(x - area.x),
                height: 1,
            };
            let paragraph = Paragraph::new(vec![line]);
            paragraph.render(text_area, buf);
        }
    }

    /// Build the info lines displayed alongside or below the art.
    fn info_lines(&self) -> Vec<Line<'static>> {
        let accent = rgb(genesis_ui::colors::UI_ACCENT);
        let dim = rgb(genesis_ui::colors::UI_DIM);
        let text_color = rgb(genesis_ui::colors::UI_TEXT);

        let title = Line::from(Span::styled(
            format!(">_ Eve v{}", self.info.version),
            Style::default().fg(accent),
        ));
        let blank = Line::from("");
        let model_line = Line::from(vec![
            Span::styled("model: ", Style::default().fg(dim)),
            Span::styled(self.info.model.clone(), Style::default().fg(text_color)),
        ]);
        let cwd_line = Line::from(vec![
            Span::styled("  cwd: ", Style::default().fg(dim)),
            Span::styled(
                truncate_path(&self.info.cwd, 40),
                Style::default().fg(text_color),
            ),
        ]);

        vec![title, blank, model_line, cwd_line]
    }
}

/// Truncate a path string to at most `max_len` characters, replacing the
/// start with "..." if needed.
fn truncate_path(path: &str, max_len: usize) -> String {
    if path.len() <= max_len {
        path.to_string()
    } else {
        let suffix = &path[path.len() - (max_len - 3)..];
        format!("...{suffix}")
    }
}

/// Compute the visual width of a ratatui Line (sum of span content widths).
fn line_visual_width(line: &Line<'_>) -> usize {
    use unicode_width::UnicodeWidthStr as _;
    line.spans.iter().map(|s| s.content.width()).sum()
}

// ── Sway animation frame generation ─────────────────────────────────────────

/// Generate 8 sway animation frames by horizontally shifting the source image.
///
/// Each frame is rendered to half-blocks and parsed into ratatui Lines. The
/// offset pattern `[0, 1, 2, 1, 0, -1, -2, -1]` creates a smooth pendulum.
fn generate_sway_frames(img: &DynamicImage) -> Vec<Vec<Line<'static>>> {
    SWAY_OFFSETS
        .iter()
        .map(|&offset| {
            let shifted = shift_image_horizontal(img, offset);
            let ansi_lines = genesis_ui::banner::render_halfblocks(&shifted);
            parse_ansi_art(&ansi_lines)
        })
        .collect()
}

/// Shift image pixels horizontally by `offset` columns.
///
/// Positive offset shifts right, negative shifts left. Pixels that fall outside
/// the canvas are clipped; the vacated area is filled with transparent pixels
/// (`Rgba([0, 0, 0, 0])`).
fn shift_image_horizontal(img: &DynamicImage, offset: i32) -> DynamicImage {
    let (width, height) = img.dimensions();
    let mut out = RgbaImage::from_pixel(width, height, Rgba([0, 0, 0, 0]));

    for y in 0..height {
        for x in 0..width {
            let src_x = x as i32 - offset;
            if src_x >= 0 && src_x < width as i32 {
                out.put_pixel(x, y, img.get_pixel(src_x as u32, y));
            }
        }
    }

    DynamicImage::ImageRgba8(out)
}

// ── ANSI → ratatui Line parser ─────────────────────────────────────────────

/// Parse ANSI-escaped half-block art strings into ratatui Lines.
pub fn parse_ansi_art(ansi_lines: &[String]) -> Vec<Line<'static>> {
    ansi_lines.iter().map(|line| parse_ansi_line(line)).collect()
}

/// Parse a single ANSI-escaped line into a ratatui Line with colored Spans.
///
/// Handles:
/// - `\x1b[38;2;R;G;Bm` — set foreground color
/// - `\x1b[48;2;R;G;Bm` — set background color
/// - `\x1b[0m` — reset all styles
/// - Combined: `\x1b[38;2;R;G;Bm\x1b[48;2;R;G;Bm` (fg then bg in sequence)
///
/// Text between escape codes is accumulated into Spans with the current style.
pub fn parse_ansi_line(s: &str) -> Line<'static> {
    let mut spans: Vec<Span<'static>> = Vec::new();
    let mut current_fg: Option<Color> = None;
    let mut current_bg: Option<Color> = None;
    let mut text_buf = String::new();
    let bytes = s.as_bytes();
    let len = bytes.len();
    let mut i = 0;

    while i < len {
        if bytes[i] == 0x1b && i + 1 < len && bytes[i + 1] == b'[' {
            // Start of an escape sequence.
            // Flush any accumulated text first.
            if !text_buf.is_empty() {
                let style = make_style(current_fg, current_bg);
                spans.push(Span::styled(std::mem::take(&mut text_buf), style));
            }

            // Find the end of the escape sequence (terminated by 'm').
            let seq_start = i + 2; // skip ESC[
            let mut seq_end = seq_start;
            while seq_end < len && bytes[seq_end] != b'm' {
                seq_end += 1;
            }
            if seq_end >= len {
                // Malformed: no terminator. Skip the ESC.
                i += 1;
                continue;
            }

            let seq = &s[seq_start..seq_end];
            if seq == "0" {
                // Reset.
                current_fg = None;
                current_bg = None;
            } else {
                // Parse semicolon-separated numbers.
                let parts: Vec<&str> = seq.split(';').collect();
                if parts.len() == 5 && parts[1] == "2" {
                    // 38;2;R;G;B or 48;2;R;G;B
                    if let (Ok(r), Ok(g), Ok(b)) = (
                        parts[2].parse::<u8>(),
                        parts[3].parse::<u8>(),
                        parts[4].parse::<u8>(),
                    ) {
                        match parts[0] {
                            "38" => current_fg = Some(Color::Rgb(r, g, b)),
                            "48" => current_bg = Some(Color::Rgb(r, g, b)),
                            _ => {}
                        }
                    }
                }
            }

            i = seq_end + 1; // skip past 'm'
        } else {
            // Regular character — accumulate.
            // Handle multi-byte UTF-8 correctly.
            let ch_start = i;
            let c = s[i..].chars().next().unwrap();
            i += c.len_utf8();
            text_buf.push_str(&s[ch_start..i]);
        }
    }

    // Flush remaining text.
    if !text_buf.is_empty() {
        let style = make_style(current_fg, current_bg);
        spans.push(Span::styled(text_buf, style));
    }

    Line::from(spans)
}

/// Build a ratatui Style from optional fg/bg colors.
fn make_style(fg: Option<Color>, bg: Option<Color>) -> Style {
    let mut style = Style::default();
    if let Some(fg) = fg {
        style = style.fg(fg);
    }
    if let Some(bg) = bg {
        style = style.bg(bg);
    }
    style
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::style::Color;

    #[test]
    fn parse_ansi_line_plain_text() {
        let line = parse_ansi_line("hello world");
        assert_eq!(line.spans.len(), 1);
        assert_eq!(line.spans[0].content, "hello world");
        assert_eq!(line.spans[0].style, Style::default());
    }

    #[test]
    fn parse_ansi_line_fg_only() {
        let input = "\x1b[38;2;255;0;128mhello\x1b[0m";
        let line = parse_ansi_line(input);
        // Should have: colored span "hello", then nothing after reset
        assert!(!line.spans.is_empty());
        assert_eq!(line.spans[0].content, "hello");
        assert_eq!(
            line.spans[0].style,
            Style::default().fg(Color::Rgb(255, 0, 128))
        );
    }

    #[test]
    fn parse_ansi_line_fg_and_bg() {
        let input = "\x1b[38;2;100;200;50m\x1b[48;2;10;20;30m▀\x1b[0m";
        let line = parse_ansi_line(input);
        assert!(!line.spans.is_empty());
        assert_eq!(line.spans[0].content, "▀");
        assert_eq!(
            line.spans[0].style,
            Style::default()
                .fg(Color::Rgb(100, 200, 50))
                .bg(Color::Rgb(10, 20, 30))
        );
    }

    #[test]
    fn parse_ansi_line_reset_clears_colors() {
        let input = "\x1b[38;2;255;0;0mred\x1b[0mplain";
        let line = parse_ansi_line(input);
        assert_eq!(line.spans.len(), 2);
        assert_eq!(line.spans[0].content, "red");
        assert_eq!(
            line.spans[0].style,
            Style::default().fg(Color::Rgb(255, 0, 0))
        );
        assert_eq!(line.spans[1].content, "plain");
        assert_eq!(line.spans[1].style, Style::default());
    }

    #[test]
    fn parse_ansi_line_mixed_halfblocks_and_spaces() {
        // Simulates: transparent space, then colored ▀, then reset + space
        let input = " \x1b[38;2;180;167;214m▀\x1b[0m ";
        let line = parse_ansi_line(input);
        // Should have: " " plain, "▀" colored, " " plain
        assert_eq!(line.spans.len(), 3);
        assert_eq!(line.spans[0].content, " ");
        assert_eq!(line.spans[1].content, "▀");
        assert_eq!(
            line.spans[1].style,
            Style::default().fg(Color::Rgb(180, 167, 214))
        );
        assert_eq!(line.spans[2].content, " ");
    }

    #[test]
    fn parse_ansi_art_multiple_lines() {
        let lines = vec![
            "\x1b[38;2;1;2;3m▄\x1b[0m".to_string(),
            "plain".to_string(),
        ];
        let parsed = parse_ansi_art(&lines);
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].spans[0].content, "▄");
        assert_eq!(parsed[1].spans[0].content, "plain");
    }

    #[test]
    fn welcome_widget_renders_full_without_panic() {
        let widget = WelcomeWidget::new(
            WelcomeInfo {
                model: "gpt-5.4".to_string(),
                cwd: "/home/user/project".to_string(),
                version: "0.1.0".to_string(),
            },
            &["\x1b[38;2;180;167;214m▀▀▀\x1b[0m".to_string()],
            &["\x1b[38;2;180;167;214m▀\x1b[0m".to_string()],
        );

        let mut buf = Buffer::empty(Rect::new(0, 0, 120, 30));
        widget.render(Rect::new(0, 0, 120, 30), &mut buf);
    }

    #[test]
    fn welcome_widget_renders_compact_without_panic() {
        let widget = WelcomeWidget::new(
            WelcomeInfo {
                model: "gpt-5.4".to_string(),
                cwd: "/home/user/project".to_string(),
                version: "0.1.0".to_string(),
            },
            &["\x1b[38;2;180;167;214m▀▀▀\x1b[0m".to_string()],
            &["\x1b[38;2;180;167;214m▀\x1b[0m".to_string()],
        );

        let mut buf = Buffer::empty(Rect::new(0, 0, 80, 24));
        widget.render(Rect::new(0, 0, 80, 24), &mut buf);
    }

    #[test]
    fn welcome_widget_renders_text_only_without_panic() {
        let widget = WelcomeWidget::new(
            WelcomeInfo {
                model: "gpt-5.4".to_string(),
                cwd: "/home/user/project".to_string(),
                version: "0.1.0".to_string(),
            },
            &[],
            &[],
        );

        let mut buf = Buffer::empty(Rect::new(0, 0, 40, 10));
        widget.render(Rect::new(0, 0, 40, 10), &mut buf);
    }

    #[test]
    fn welcome_widget_zero_area_does_not_panic() {
        let widget = WelcomeWidget::new(
            WelcomeInfo {
                model: "m".to_string(),
                cwd: "/".to_string(),
                version: "0".to_string(),
            },
            &[],
            &[],
        );

        let mut buf = Buffer::empty(Rect::new(0, 0, 1, 1));
        widget.render(Rect::new(0, 0, 0, 0), &mut buf);
    }

    #[test]
    fn truncate_path_short_unchanged() {
        assert_eq!(truncate_path("/home/user", 40), "/home/user");
    }

    #[test]
    fn truncate_path_long_gets_ellipsis() {
        let long = "/home/user/very/deeply/nested/project/src/main.rs";
        let result = truncate_path(long, 20);
        assert!(result.starts_with("..."));
        assert_eq!(result.len(), 20);
    }

    #[test]
    fn info_lines_contain_version_and_model() {
        let widget = WelcomeWidget::new(
            WelcomeInfo {
                model: "claude-4".to_string(),
                cwd: "/tmp".to_string(),
                version: "1.2.3".to_string(),
            },
            &[],
            &[],
        );
        let lines = widget.info_lines();
        // Title line should contain version.
        let title_text: String = lines[0].spans.iter().map(|s| s.content.as_ref()).collect();
        assert!(title_text.contains("1.2.3"));
        // Model line (index 2 since index 1 is blank).
        let model_text: String = lines[2].spans.iter().map(|s| s.content.as_ref()).collect();
        assert!(model_text.contains("claude-4"));
    }

    // ── Sway animation tests ───────────────────────────────────────────

    #[test]
    fn shift_image_zero_offset_is_identity() {
        // Create a 4x2 image with a known pixel pattern.
        let mut img = RgbaImage::new(4, 2);
        img.put_pixel(0, 0, Rgba([255, 0, 0, 255]));
        img.put_pixel(1, 0, Rgba([0, 255, 0, 255]));
        img.put_pixel(2, 0, Rgba([0, 0, 255, 255]));
        img.put_pixel(3, 0, Rgba([128, 128, 128, 255]));
        let dyn_img = DynamicImage::ImageRgba8(img.clone());

        let shifted = shift_image_horizontal(&dyn_img, 0);
        let shifted_rgba = shifted.to_rgba8();

        for y in 0..2 {
            for x in 0..4 {
                assert_eq!(
                    shifted_rgba.get_pixel(x, y),
                    img.get_pixel(x, y),
                    "mismatch at ({x}, {y})"
                );
            }
        }
    }

    #[test]
    fn shift_image_positive_shifts_right() {
        // 4x1 image: [R, G, B, W]
        let mut img = RgbaImage::new(4, 1);
        img.put_pixel(0, 0, Rgba([255, 0, 0, 255]));   // R
        img.put_pixel(1, 0, Rgba([0, 255, 0, 255]));   // G
        img.put_pixel(2, 0, Rgba([0, 0, 255, 255]));   // B
        img.put_pixel(3, 0, Rgba([255, 255, 255, 255]));// W
        let dyn_img = DynamicImage::ImageRgba8(img);

        // Shift right by 1: result should be [transparent, R, G, B]
        let shifted = shift_image_horizontal(&dyn_img, 1);
        let out = shifted.to_rgba8();

        // x=0 should be transparent
        assert_eq!(out.get_pixel(0, 0)[3], 0);
        // x=1 should be R
        assert_eq!(*out.get_pixel(1, 0), Rgba([255, 0, 0, 255]));
        // x=2 should be G
        assert_eq!(*out.get_pixel(2, 0), Rgba([0, 255, 0, 255]));
        // x=3 should be B
        assert_eq!(*out.get_pixel(3, 0), Rgba([0, 0, 255, 255]));
    }

    #[test]
    fn generate_sway_frames_produces_8_frames() {
        // Use a small synthetic image to keep the test fast.
        let img = DynamicImage::new_rgba8(8, 4);
        let frames = generate_sway_frames(&img);
        assert_eq!(frames.len(), 8);
    }

    #[test]
    fn next_frame_cycles() {
        let widget_info = WelcomeInfo {
            model: "test".to_string(),
            cwd: "/tmp".to_string(),
            version: "0.0.0".to_string(),
        };
        let mut widget = WelcomeWidget::new(widget_info, &[], &[]);

        // Widget should be animated since the embedded images are available.
        assert!(widget.animated);
        assert_eq!(widget.current_frame, 0);

        // Advance through all 8 frames and verify wrap-around.
        for expected in 1..=8 {
            widget.next_frame();
            assert_eq!(widget.current_frame, expected % 8);
        }
        // After 8 advances we should be back at 0.
        assert_eq!(widget.current_frame, 0);
    }
}
