[package]
name = "genesis-provider"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-stream.workspace = true
futures-util.workspace = true
genesis-auth = { path = "../genesis-auth" }
genesis-types = { path = "../genesis-types" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
regex.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
insta = { workspace = true }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-test.workspace = true
