[package]
name = "genesis"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
genesis-cli = { path = "../../crates/genesis-cli" }
genesis-tui = { path = "../../crates/genesis-tui" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
